apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-green
  labels:
    app: webapp-green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp-green
  template:
    metadata:
      labels:
        app: webapp-green
    spec:
      containers:
        - name: capstone
          image: ylabanieh/capstone:latest
          ports:
            - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp-green
  ports:
    - protocol: TCP
      port: 80
  type: LoadBalancer
---