apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::198533582888:role/Ec2S3CloudWatchFullAccess
      username: system:node:ip-172-31-41-177.us-east-2.compute.internal
      groups:
        - system:bootstrappers
        - system:nodes